# Generated by Django 5.2.7 on 2025-10-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Количество раз, когда товары были куплены вместе', verbose_name='Частота совместных покупок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='shop.product', verbose_name='Товар 1')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='shop.product', verbose_name='Товар 2')),
            ],
            options={
                'verbose_name': 'Статистика рекомендаций',
                'verbose_name_plural': 'Статистика рекомендаций',
                'indexes': [models.Index(fields=['product1', '-frequency'], name='recommendat_product_0f9ead_idx'), models.Index(fields=['product2', '-frequency'], name='recommendat_product_fafc19_idx')],
                'unique_together': {('product1', 'product2')},
            },
        ),
    ]
